/* Intl upgrade */

/*
GAME DATA
*/

DROP TABLE IF EXISTS games;
CREATE TABLE games (
game_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
rating INT(32) UNSIGNED NOT NULL DEFAULT 0,
published TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
type ENUM('LOCATION','ANYWHERE','QR'),
intro_scene_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
latitude DOUBLE NOT NULL DEFAULT 0.0,
longitude DOUBLE NOT NULL DEFAULT 0.0,
/* tab data */
    /* map */
map_type enum('STREET','SATELLITE','HYBRID') NOT NULL DEFAULT 'STREET',
map_latitude DOUBLE NOT NULL DEFAULT 0.0,
map_longitude DOUBLE NOT NULL DEFAULT 0.0,
map_zoom_level DOUBLE NOT NULL DEFAULT 0.0,
map_show_player TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
map_show_players TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
map_offsite_mode TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    /* notes */
notebook_allow_comments TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
notebook_allow_likes TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
notebook_allow_player_tags TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    /* inventory */
inventory_weight_cap INT(32) NOT NULL DEFAULT -1,

created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS tabs;
CREATE TABLE tabs (
tab_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
type ENUM('MAP','DECODER','SCANNER','QUESTS','INVENTORY','PLAYER','NOTEBOOK','NOTE','DIALOG','ITEM','PLAQUE','WEB_PAGE') NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
content_id INT(32) UNSIGNED NOT NULL,
info VARCHAR(255) NOT NULL DEFAULT "",
requirement_root_package_id INT(32) UNSIGNED NOT NULL,
sort_index INT(32) NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX tab_game_id ON tabs(game_id);

DROP TABLE IF EXISTS event_packages;
CREATE TABLE event_packages (
event_package_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX event_package_game_id ON event_packages(game_id);

DROP TABLE IF EXISTS events;
CREATE TABLE events (
event_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
event_package_id INT(32) UNSIGNED NOT NULL,
event ENUM('GIVE_ITEM','TAKE_ITEM') NOT NULL DEFAULT 'GIVE_ITEM',
content_id INT(32) UNSIGNED NOT NULL,
qty INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX event_game_id ON events(game_id);

DROP TABLE IF EXISTS items;
CREATE TABLE items (
item_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
droppable TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
destroyable TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
max_qty_in_inventory INT(32) NOT NULL DEFAULT -1,
weight INT(32) UNSIGNED NOT NULL DEFAULT 0,
url TINYTEXT NOT NULL,
type ENUM('NORMAL','ATTRIB','URL') NOT NULL DEFAULT 'NORMAL',
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX item_game_id ON items(game_id);

DROP TABLE IF EXISTS dialogs;
CREATE TABLE dialogs (
dialog_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
intro_dialog_script_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX dialog_game_id ON dialogs(game_id);

DROP TABLE IF EXISTS dialog_characters;
CREATE TABLE dialog_characters (
dialog_character_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
name VARCHAR(255) NOT NULL DEFAULT "",
title VARCHAR(255) NOT NULL DEFAULT "",
media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX dialog_character_game_id ON dialog_characters(game_id);

DROP TABLE IF EXISTS dialog_scripts;
CREATE TABLE dialog_scripts (
dialog_script_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
dialog_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
dialog_character_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
text TEXT NOT NULL,
event_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX dialog_script_game_id ON dialog_scripts(game_id);
CREATE INDEX dialog_script_dialog_id ON dialog_scripts(dialog_id);

DROP TABLE IF EXISTS dialog_options;
CREATE TABLE dialog_options (
dialog_option_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
dialog_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
parent_dialog_script_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
prompt VARCHAR(255) NOT NULL DEFAULT "",
link_type ENUM('DIALOG_SCRIPT','EXIT','EXIT_TO_PLAQUE','EXIT_TO_ITEM','EXIT_TO_WEB_PAGE','EXIT_TO_DIALOG','EXIT_TO_TAB') DEFAULT 'DIALOG_SCRIPT',
link_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
link_info VARCHAR(255) NOT NULL DEFAULT "",
requirement_root_package_id INT(32) UNSIGNED NOT NULL,
sort_index INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX dialog_option_game_id ON dialog_options(game_id);
CREATE INDEX dialog_option_dialog_id ON dialog_options(dialog_id);

DROP TABLE IF EXISTS plaques;
CREATE TABLE plaques (
plaque_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
event_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX plaque_game_id ON plaques(game_id);

DROP TABLE IF EXISTS web_pages;
CREATE TABLE web_pages (
web_page_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL,
icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
url TINYTEXT NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX web_page_game_id ON web_pages(game_id);

DROP TABLE IF EXISTS tags;
CREATE TABLE tags (
tag_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
tag VARCHAR(255) NOT NULL DEFAULT '',
media_id INT(32) UNSIGNED NOT NULL DEFAULT '0',
visible TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
player_created TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
sort_index INT(32) NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX tag_game_id ON tags(game_id);

DROP TABLE IF EXISTS object_tags;
CREATE TABLE object_tags (
object_tag_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
object_type ENUM('PLAQUE','ITEM','DIALOG','WEB_PAGE'),
object_id INT(32) UNSIGNED NOT NULL,
tag_id INT(32) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX object_tag_object ON object_tags(game_id, object_type, object_id);
CREATE INDEX object_tag_tag ON object_tags(game_id, tag_id);

DROP TABLE IF EXISTS web_hooks;
CREATE TABLE web_hooks (
web_hook_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
url TINYTEXT NOT NULL,
incoming TINYINT(1) NOT NULL DEFAULT '0',
requirement_root_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX web_hook_game_id ON web_hooks(game_id);

DROP TABLE IF EXISTS overlays;
CREATE TABLE overlays (
overlay_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
media_id INT(32) UNSIGNED NOT NULL,
top_left_latitude DOUBLE NOT NULL DEFAULT 0.0,
top_left_longitude DOUBLE NOT NULL DEFAULT 0.0,
top_right_latitude DOUBLE NOT NULL DEFAULT 0.0,
top_right_longitude DOUBLE NOT NULL DEFAULT 0.0,
bottom_left_latitude DOUBLE NOT NULL DEFAULT 0.0,
bottom_left_longitude DOUBLE NOT NULL DEFAULT 0.0,
requirement_root_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX overlay_game_id ON overlays(game_id);

DROP TABLE IF EXISTS notes;
CREATE TABLE notes (
note_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
user_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
label_id INT(32) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX note_game_id ON notes(game_id);
CREATE INDEX note_user_id ON notes(user_id);

CREATE TABLE quests (
quest_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
active_icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
active_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
active_description TEXT NOT NULL,
active_notification_type ENUM('NONE','FULL_SCREEN','DROP_DOWN'),
active_function ENUM('NONE','MAP','DECODER','SCANNER','QUESTS','INVENTORY','PLAYER','NOTEBOOK','PICKGAME','JAVASCRIPT') NOT NULL DEFAULT 'NONE',
active_event_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
active_requirement_root_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
complete_icon_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
complete_media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
complete_description TEXT NOT NULL,
complete_notification_type ENUM('NONE','FULL_SCREEN','DROP_DOWN'),
complete_function ENUM('NONE','MAP','DECODER','SCANNER','QUESTS','INVENTORY','PLAYER','NOTEBOOK','PICKGAME','JAVASCRIPT') NOT NULL DEFAULT 'NONE',
complete_event_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
complete_requirement_root_package_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
sort_index INT(32) UNSIGNED NOT NULL DEFAULT '0',
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX quest_game_id ON quests(game_id);

DROP TABLE IF EXISTS media;
CREATE TABLE media (
media_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
user_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
name VARCHAR(255) DEFAULT "",
file_folder VARCHAR(255) NOT NULL DEFAULT "",
file_name VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX media_game_id ON media(game_id);

DROP TABLE IF EXISTS scenes;
CREATE TABLE scenes (
scene_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX scene_game ON scenes(game_id);

DROP TABLE IF EXISTS instances;
CREATE TABLE instances (
instance_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
object_type ENUM('PLAQUE','ITEM','DIALOG','WEB_PAGE','NOTE','FACTORY','SCENE'),
object_id INT(32) UNSIGNED NOT NULL,
qty INT(32) UNSIGNED NOT NULL DEFAULT 0,
infinite_qty TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
factory_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
owner_id INT(32) UNSIGNED NOT NULL DEFAULT 0, /* 0 for 'owned by the world' */
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX instance_object ON instances(object_type, object_id);
CREATE INDEX instance_game_owner ON instances(game_id, owner_id);

DROP TABLE IF EXISTS triggers;
CREATE TABLE triggers (
trigger_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
instance_id INT(32) UNSIGNED NOT NULL,
scene_id INT(32) UNSIGNED NOT NULL,
requirement_root_package_id INT(32) UNSIGNED NOT NULL,
type ENUM('IMMEDIATE','LOCATION','QR'),
name VARCHAR(255) NOT NULL DEFAULT "",
title VARCHAR(255) NOT NULL DEFAULT "",
icon_media_id INT(32) NOT NULL DEFAULT 0,
latitude DOUBLE NOT NULL DEFAULT 0.0,
longitude DOUBLE NOT NULL DEFAULT 0.0,
distance INT(32) NOT NULL DEFAULT 0,
wiggle TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
show_title TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
hidden TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
trigger_on_enter TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
qr_code VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX trigger_instance ON triggers(instance_id);
CREATE INDEX trigger_scene ON triggers(scene_id);
CREATE INDEX trigger_game ON triggers(game_id);

DROP TABLE IF EXISTS factories;
CREATE TABLE factories (
factory_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
name VARCHAR(255) NOT NULL DEFAULT "",
description TEXT NOT NULL,
object_type ENUM('PLAQUE','ITEM','DIALOG','WEB_PAGE'),
object_id INT(32) UNSIGNED NOT NULL,
seconds_per_production INT(32) UNSIGNED NOT NULL DEFAULT 0,
production_probability DOUBLE NOT NULL DEFAULT 1.0,
max_production INT(32) UNSIGNED NOT NULL DEFAULT 0,
produce_expiration_time INT(32) UNSIGNED NOT NULL DEFAULT 100,
produce_expire_on_view TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
production_bound_type ENUM('PER_PLAYER','TOTAL'),
location_bound_type ENUM('PLAYER','LOCATION'),
min_production_distance INT(32) NOT NULL DEFAULT 0,
max_production_distance INT(32) NOT NULL DEFAULT 0,
requirement_root_package_id INT(32) UNSIGNED NOT NULL, /*requirement to produce trigger*/
production_timestamp TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
trigger_latitude DOUBLE NOT NULL DEFAULT 0.0,
trigger_longitude DOUBLE NOT NULL DEFAULT 0.0,
trigger_distance INT(32) NOT NULL DEFAULT 0,
trigger_on_enter TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
trigger_hidden TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
trigger_wiggle TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
trigger_title VARCHAR(255) NOT NULL DEFAULT "",
trigger_icon_media_id INT(32) NOT NULL DEFAULT 0,
trigger_show_title TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
trigger_requirement_root_package_id INT(32) UNSIGNED NOT NULL, /*requirement to view spawned trigger*/
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX factory_game ON factories(game_id);

DROP TABLE IF EXISTS requirement_root_packages;
CREATE TABLE requirement_root_packages (
requirement_root_package_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX requirement_root_package_game ON requirement_root_packages(game_id);

DROP TABLE IF EXISTS requirement_and_packages;
CREATE TABLE requirement_and_packages (
requirement_and_package_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
requirement_root_package_id INT(32) UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL DEFAULT "",
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX and_requirement_root_package ON requirement_and_packages(requirement_root_package_id);
CREATE INDEX and_requirement_game ON requirement_and_packages(game_id);

DROP TABLE IF EXISTS requirement_atoms;
CREATE TABLE requirement_atoms (
requirement_atom_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
game_id INT(32) UNSIGNED NOT NULL,
requirement_and_package_id INT(32) UNSIGNED NOT NULL,
bool_operator TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
requirement ENUM('ALWAYS_TRUE','ALWAYS_FALSE','PLAYER_HAS_ITEM','PLAYER_HAS_TAGGED_ITEM','PLAYER_VIEWED_ITEM','PLAYER_VIEWED_PLAQUE','PLAYER_VIEWED_DIALOG','PLAYER_VIEWED_DIALOG_SCRIPT','PLAYER_VIEWED_WEB_PAGE','PLAYER_HAS_UPLOADED_MEDIA_ITEM','PLAYER_HAS_UPLOADED_MEDIA_ITEM_IMAGE','PLAYER_HAS_UPLOADED_MEDIA_ITEM_AUDIO','PLAYER_HAS_UPLOADED_MEDIA_ITEM_VIDEO','PLAYER_HAS_COMPLETED_QUEST','PLAYER_HAS_RECEIVED_INCOMING_WEB_HOOK','PLAYER_HAS_NOTE','PLAYER_HAS_NOTE_WITH_TAG','PLAYER_HAS_NOTE_WITH_LIKES','PLAYER_HAS_NOTE_WITH_COMMENTS','PLAYER_HAS_GIVEN_NOTE_COMMENTS'),
content_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
distance INT(32) NOT NULL DEFAULT 0,
qty INT(32) UNSIGNED NOT NULL DEFAULT 0,
latitude DOUBLE NOT NULL DEFAULT 0.0,
longitude DOUBLE NOT NULL DEFAULT 0.0,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX atom_requirement_and_package ON requirement_atoms(requirement_and_package_id);
CREATE INDEX atom_requirement_game ON requirement_atoms(game_id);

/*
USER DATA
*/

DROP TABLE IF EXISTS users;
CREATE TABLE users (
user_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(255) NOT NULL DEFAULT "",
display_name VARCHAR(255) NOT NULL DEFAULT "",
email VARCHAR(255) NOT NULL DEFAULT "",
media_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
hash VARCHAR(255) NOT NULL,
salt VARCHAR(255) NOT NULL,
read_key VARCHAR(255) NOT NULL,
write_key VARCHAR(255) NOT NULL,
read_write_key VARCHAR(255) NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX user_user_name ON users(user_name);
CREATE INDEX user_email ON users(email);

DROP TABLE IF EXISTS user_games;
CREATE TABLE user_games (
game_id INT(32) UNSIGNED NOT NULL DEFAULT '0',
user_id INT(32) UNSIGNED NOT NULL DEFAULT '0',
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, game_id)
);
CREATE INDEX user_game_game_id ON user_games(game_id);

DROP TABLE IF EXISTS user_game_scenes;
CREATE TABLE user_game_scenes (
user_id INT(32) UNSIGNED NOT NULL,
game_id INT(32) UNSIGNED NOT NULL,
scene_id INT(32) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, game_id)
);

DROP TABLE IF EXISTS user_log;
CREATE TABLE user_log (
user_log_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
game_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
event_type ENUM(
'LOG_IN','BEGIN_GAME','RESET_GAME','MOVE',
'RECEIVE_ITEM','LOSE_ITEM',
'VIEW_TAB','VIEW_INSTANCE','VIEW_PLAQUE','VIEW_ITEM','VIEW_DIALOG','VIEW_DIALOG_SCRIPT','VIEW_WEB_PAGE','VIEW_NOTE','VIEW_SCENE',
'TRIGGER_TRIGGER','CHANGE_SCENE','COMPLETE_QUEST',
'CREATE_NOTE','GIVE_NOTE_LIKE','GET_NOTE_LIKE','GIVE_NOTE_COMMENT','GET_NOTE_COMMENT',
'UPLOAD_MEDIA_ITEM','UPLOAD_MEDIA_ITEM_IMAGE','UPLOAD_MEDIA_ITEM_AUDIO','UPLOAD_MEDIA_ITEM_VIDEO',
'RECEIVE_WEBHOOK','SEND_WEBHOOK'
),
content_id INT(32) UNSIGNED NOT NULL DEFAULT 0,
qty INT(32) UNSIGNED NOT NULL DEFAULT 0,
latitude DOUBLE NOT NULL DEFAULT 0.0,
longitude DOUBLE NOT NULL DEFAULT 0.0,
deleted TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP /* no 'last active', as rows are immutable */
);
CREATE INDEX user_log_check ON user_log(user_id, game_id, event_type, deleted);
CREATE INDEX user_log_user_id ON user_log(user_id, created);
CREATE INDEX user_log_game_id ON user_log(game_id, created);

