ALTER TABLE events CHANGE event event ENUM('GIVE_ITEM','TAKE_ITEM','GIVE_ITEM_PLAYER','TAKE_ITEM_PLAYER','GIVE_ITEM_GAME','TAKE_ITEM_GAME');
UPDATE events SET event = 'GIVE_ITEM_PLAYER' WHERE event = 'GIVE_ITEM';
UPDATE events SET event = 'TAKE_ITEM_PLAYER' WHERE event = 'TAKE_ITEM';
ALTER TABLE events CHANGE event event ENUM('GIVE_ITEM_PLAYER','TAKE_ITEM_PLAYER','GIVE_ITEM_GAME','TAKE_ITEM_GAME');
