ALTER TABLE events CHANGE event event ENUM('NONE','GIVE_ITEM_PLAYER','TAKE_ITEM_PLAYER','SET_ITEM_PLAYER','GIVE_ITEM_GAME','TAKE_ITEM_GAME','SET_ITEM_GAME','GIVE_ITEM_GROUP','TAKE_ITEM_GROUP','SET_ITEM_GROUP','SET_SCENE','SET_GROUP','RUN_SCRIPT') NOT NULL DEFAULT 'NONE';
ALTER TABLE events ADD script TEXT DEFAULT "" AFTER qty;
