ALTER TABLE triggers CHANGE type type ENUM('IMMEDIATE','LOCATION','QR','TIMER','AR') NOT NULL DEFAULT 'IMMEDIATE';
ALTER TABLE triggers ADD vr_target_id INT(32) UNSIGNED NOT NULL DEFAULT 0 AFTER seconds;
CREATE TABLE vr_targets ( vr_target_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, game_id INT(32) UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL DEFAULT "", vuforia_index INT(32) UNSIGNED NOT NULL, created TIMESTAMP DEFAULT '0000-00-00 00:00:00', last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
